services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    image: spear-ansible-test
    working_dir: /workspace
    volumes:
      - ./../../:/workspace
    command:
      - ansible-playbook
      - -i
      - inventory.yml
      - site.yml
      - --limit
      - docker