all:
  hosts:
    container_local:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: root
      prefix_path: /opt/sselabs
      is_pipeline: true
      skip_phasar: true

    docker:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: root
      prefix_path: /opt/sselabs
      is_pipeline: true
      skip_phasar: false

    device01:
      ansible_user: spear
      ansible_host: 192.168.0.115
      ansible_connection: ssh
      ansible_ssh_private_key_file: ./.ssh_deploy_key
      ansible_python_interpreter: /usr/bin/python3
      prefix_path: /opt/sselabs
      is_pipeline: false
      skip_phasar: false

    device02:
      ansible_user: spear
      ansible_host: 192.168.0.57
      ansible_connection: ssh
      ansible_ssh_private_key_file: ./.ssh_deploy_key
      ansible_python_interpreter: /usr/bin/python3
      prefix_path: /opt/sselabs
      is_pipeline: false
      skip_phasar: false

    device03:
        ansible_user: spear
        ansible_host: 192.168.0.71
        ansible_connection: ssh
        ansible_ssh_private_key_file: ./.ssh_deploy_key
        ansible_python_interpreter: /usr/bin/python3
        prefix_path: /opt/sselabs
        is_pipeline: false
        skip_phasar: false

    device04:
        ansible_user: spear
        ansible_host: 192.168.178.73
        ansible_connection: ssh
        ansible_ssh_private_key_file: ./.ssh_deploy_key
        ansible_python_interpreter: /usr/bin/python3
        prefix_path: /opt/sselabs
        is_pipeline: false
        skip_phasar: false

    device05:
        ansible_user: spear
        ansible_host: 192.168.0.116
        ansible_connection: ssh
        ansible_ssh_private_key_file: ./.ssh_deploy_key
        ansible_python_interpreter: /usr/bin/python3
        prefix_path: /opt/sselabs
        is_pipeline: false
        skip_phasar: false